#!/bin/bash
set -euo pipefail

TRAINING_FILE=${TRAINING_FILE:-/local/norman/UHHAnalysis/SPANet/hdf5/22pre_v14_vbf_signal_all.h5}
VALIDATION_FILE=${VALIDATION_FILE:-}
RUN_NAME=${RUN_NAME:-vbf_hh_bbtautau_train}
EPOCHS=${EPOCHS:-50}
BATCH_SIZE=${BATCH_SIZE:-256}
DIAGNOSTICS_BATCHES=${DIAGNOSTICS_BATCHES:-10}
FP16=${FP16:-0}
VALIDATE_EVERY_N_EPOCHS=${VALIDATE_EVERY_N_EPOCHS:-1}
LOG_EVERY_N_STEPS=${LOG_EVERY_N_STEPS:-50}
DEVICE_STATS=${DEVICE_STATS:-0}
CHECKPOINT=${CHECKPOINT:-}
EVENT_FILE=${EVENT_FILE:-event_files/vbf_hh_bbtautau.yaml}

sbatch \
    --job-name="${RUN_NAME}" \
    --export=ALL,TRAINING_FILE="${TRAINING_FILE}",VALIDATION_FILE="${VALIDATION_FILE}",RUN_NAME="${RUN_NAME}",EPOCHS="${EPOCHS}",BATCH_SIZE="${BATCH_SIZE}",DIAGNOSTICS_BATCHES="${DIAGNOSTICS_BATCHES}",FP16="${FP16}",VALIDATE_EVERY_N_EPOCHS="${VALIDATE_EVERY_N_EPOCHS}",LOG_EVERY_N_STEPS="${LOG_EVERY_N_STEPS}",DEVICE_STATS="${DEVICE_STATS}",CHECKPOINT="${CHECKPOINT}",EVENT_FILE="${EVENT_FILE}" \
    scripts/train_vbf_hh_bbtautau_gpu.sh
